### ISSUE TITLE
Latest version missing in Pub

### ISSUE THREAD

**Issue by kostaa** [marcglasberg/provider_for_redux#7]
Would you be able to to push the latest version to the 'Pub' please? 
Could you also set the 'async_redux' dependency to the latest version if that works?

Many thanks
Adam

**Comment by marcglasberg** [comment]
Done! I apologize for taking so much time to close this. It seems GitHub is not emailing me of new issues in my packages, for some reason.

Don't forget you usually can choose the version yourself, like so, in your `pubspec.yaml`:

    dependency_overrides:
      async_redux: ^13.0.0
